### ISSUE TITLE
구독봇 옛날 영상 올림?

### ISSUE THREAD

**Issue by RTFTR** [skinmaker1345/subscriber-bot#2]
구독봇이 예전에 올렸던 영상을 최근에 올린 영상으로 착각합니다
![Screenshot_20231022_172456_Discord](https://github.com/skinmaker1345/subscriber-bot/assets/83257329/ae4ad0ed-e7d2-45f8-aaf1-0f17238f439f)

**Comment by skinmaker1345** [comment]
@RTFTR 
해당 문제는 유튜브 측 문제로 확인되었습니다.
오늘(22일) 아침부로 해당 문제를 해결하기 위해 추가적인 검증 절차를 도입하였습니다.
또한 본 레포지토리는 사용 문서 게재 외 다른 용도로는 사용하지 않습니다.
봇에 대한 문제가 있거나 각종 문의가 있으시다면 DM을 통해 제보해주세요.
